version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-2)
      - aws ecr create-repository --repository-name ajalasimpleply 
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...   
      - docker build -t ajalasimpleply:master .
      - docker tag ajalasimpleply:master 351308386317.dkr.ecr.eu-west-2.amazonaws.com/ajalasimpleply:master      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push 351308386317.dkr.ecr.eu-west-2.amazonaws.com/ajalasimpleply:master